name: Scala CI

on:
  pull_request:
    branches: [ main ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    # Instalar Java JDK versión 11
    - name: Instalar JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
   
    # Iniciar Test, Compilación y Empaquetado
    - name: Run tests
      run: sbt test
    - name: Run Build
      run: sbt compile
    - name: Run Package
      run: sbt package

    # Instalar Credenciales CLI de Google Cloud Platform        
    - name: Instalar cli GCP
      uses: google-github-actions/setup-gcloud@v0

    - uses: actions-hub/gcloud@master
      name: Enviar archivo Jar a Datastorage
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      with:
        args: cp target/scala-2.12/proyecto_test_2.12-0.1.jar gs://dataproc-test-bdb/
        cli: gsutil

    - uses: actions-hub/gcloud@master
      name: Enviar Datastorage a jobs dataproc
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      with:
        args: dataproc job submit spark --cluster=cluster-dd7b --region=us-central1 --jars=gs://dataproc-test-bdb/proyecto_test_2.12-0.1.jar --class=hello.class

    - uses: actions-hub/gcloud@master
      name: Eliminar archivo Jar a Datastorage
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      with:
        args: rm gs://dataproc-test-bdb/proyecto_test_2.12-0.1.jar
        cli: gsutil
