name: Scala CI

on:
  pull_request:
    branches: [ main ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    # Instalar Java JDK versión 11
    - name: Instalar JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    # Instalar CLI de Google Cloud Platform
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: Instalar cli GCP
      uses: google-github-actions/setup-gcloud@v0
        
    - name: Run tests
      run: sbt test
    - name: Run Build
      run: sbt compile
