name: Scala CI

on:
  pull_request:
    branches: [ main ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    # Instalar Java JDK versión 11
    - name: Instalar JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    # Instalar CLI de Google Cloud Platform    
    - name: Instalar cli GCP
      uses: actions-hub/gcloud@360.0.0
      env:
        PROJECT_ID: nimbus-dashboard-340420
        APPLICATION_CREDENTIALS: nimbus-dashboard-340420-4b2bf2da9668.json
      with:
        args: info      
    - name: Run tests
      run: sbt test
    - name: Run Build
      run: sbt build
